<?php

/**
 * @file
 * Contains fontawesome_menu_icons.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Render\FormattableMarkup;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_help().
 */
function fontawesome_menu_icons_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fontawesome_menu_icons module.
    case 'help.page.fontawesome_menu_icons':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('FontAwesome Menu Icons') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function fontawesome_menu_icons_form_menu_link_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $menu_link = $form_state->getFormObject()->getEntity();
  $menu_link_options = $menu_link->link->first()->options ?: [];

  $form['fa_icon'] = array(
    '#type'          => 'textfield',
    '#title'         => t('FontAwesome Icon'),
    '#default_value' => !empty($menu_link_options['fa_icon']) ? $menu_link_options['fa_icon'] : '',
    '#attributes'    => [
      'class' => [
        'fa-menu-iconpicker',
      ],
    ],
  );

  $form['actions']['submit']['#submit'][] = 'fontawesome_menu_icons_menu_link_content_form_submit';

  // FIXME 'libraries/fontawesome-iconpicker' doesn't work...
  // @see https://www.drupal.org/docs/8/modules/libraries-api-8x/using-libraries-api-3x-as-a-module-developer
  // $form['#attached']['library'][] = 'libraries/fontawesome-iconpicker';

  $form['#attached']['library'][] = 'fontawesome_menu_icons/fontawesome-iconpicker';
  $form['#attached']['library'][] = 'fontawesome_menu_icons/fontawesome-menu-icons';
}

/**
 * Process the submitted form.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function fontawesome_menu_icons_menu_link_content_form_submit($form, FormStateInterface $form_state) {
  $icon_field = $form_state->getValue('fa_icon');
  $icon = empty($icon_field) ? '' : $icon_field;

  $options = [
    'fa_icon' => Html::escape($icon),
  ];

  $menu_link = $form_state->getFormObject()->getEntity();
  $menu_link_options = $menu_link->link->first()->options;

  $merged = array_merge($menu_link_options, $options);

  $menu_link->link->first()->options = $merged;
  $menu_link->save();
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function fontawesome_menu_icons_form_menu_link_edit_alter(&$form, FormStateInterface $form_state, $form_id) {
  $options = $form_state->getBuildInfo()['args'][0]->getOptions();

  $form['fa_icon'] = array(
    '#type'          => 'textfield',
    '#title'         => t('FontAwesome Icon'),
    '#default_value' => !empty($options['fa_icon']) ? $options['fa_icon'] : '',
    '#attributes'    => [
      'class' => [
        'fa-menu-iconpicker',
      ],
    ],
  );

  $form['actions']['submit']['#submit'][] = 'fontawesome_menu_icons_form_menu_link_edit_submit';

  // FIXME 'libraries/fontawesome-iconpicker' doesn't work...
  // @see https://www.drupal.org/docs/8/modules/libraries-api-8x/using-libraries-api-3x-as-a-module-developer
  // $form['#attached']['library'][] = 'libraries/fontawesome-iconpicker';

  $form['#attached']['library'][] = 'fontawesome_menu_icons/fontawesome-iconpicker';
  $form['#attached']['library'][] = 'fontawesome_menu_icons/fontawesome-menu-icons';
}

/**
 * Process the submitted form.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function fontawesome_menu_icons_form_menu_link_edit_submit($form, FormStateInterface $form_state) {
  $options = $form_state->getBuildInfo()['args'][0]->getOptions();

  $fa_icon = $form_state->getValue('fa_icon');

  if (empty($fa_icon)) {
    $options['fa_icon'] = '';
  }
  else {
    $options['fa_icon'] = Html::escape($fa_icon);
  }

  $menu_link_id = $form_state->getValue('menu_link_id');

  /* @var \Drupal\Core\Menu\MenuLinkManager $menu_link_manager */
  // $menu_link_manager = \Drupal::service('plugin.manager.menu.link');
  // $menu_link_manager->updateDefinition($menu_link_id, ['options' => $options]);

  // FIXME
  // Use $menu_link_manager->updateDefinition()... but it does not work...
  if (!empty($menu_link_id)) {
    // FIXME
    // After clearing the site's cache, the options were cleared from the
    // database table... why?!
    $query = \Drupal::database()->update('menu_tree');
    $query->fields([
      'options' => serialize($options),
    ]);
    $query->condition('id', $menu_link_id);
    $query->execute();


    $config_factory = \Drupal::configFactory();
    $config = $config_factory->getEditable('fontawesome_menu_icons.settings');

    $icons = $config->get('menu_link_icons');
    // Array key cannot contain dot in the config.
    $config_key = str_replace('.', '_', $menu_link_id);

    if (empty($options['fa_icon'])) {
      if (isset($icons[$config_key])) {
        unset($icons[$config_key]);
      }
    }
    else {
      $icons[$config_key] = $options['fa_icon'];
    }

    $config->set('menu_link_icons', $icons);
    $config->save();
  }
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function fontawesome_menu_icons_menu_links_discovered_alter(&$links) {
  // After clearing the site's cache, the options were cleared from the
  // menu_tree database table (I'm not sure if this is a bug or normal
  // behaviour)... but we need to re-apply fa_icon on each menu link item.

  $config = \Drupal::config('fontawesome_menu_icons.settings');
  $icons = $config->get('menu_link_icons');

  foreach ($links as &$link) {
    if (empty($link['id'])) {
      continue;
    }

    // Array key cannot contain dot in the config.
    $config_key = str_replace('.', '_', $link['id']);

    if (!empty($icons[$config_key])) {
      $link['options']['fa_icon'] = $icons[$config_key];
    }
  }
}

/**
 * Implements hook_link_alter().
 */
function fontawesome_menu_icons_link_alter(&$variables) {
  if (!empty($variables['options']['fa_icon']) && empty($variables['options']['already_processed'])) {
    $class = $variables['options']['fa_icon'];

    $variables['text'] = new FormattableMarkup('<i class="fa ' . $class . '"></i> @title', [
      '@title' => $variables['text'],
    ]);

    $variables['options']['already_processed'] = TRUE;
  }
}
