icons.icon_set.*:
  type: config_entity
  label: 'Icon Set config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    plugin:
      type: string
      label: 'Plugin'
    settings:
      type: icon_set.settings.[%parent.plugin]

field.formatter.settings.list_icon:
  type: mapping
  label: 'Icon format settings'

field.widget.settings.icon_select:
  type: mapping
  label: 'Select icon list format settings'

field.storage_settings.list_icon:
  type: mapping
  label: 'List (icon) settings'
  mapping:
    allowed_values_function:
      type: string
      label: 'Allowed values function'

field.field_settings.list_icon:
  label: 'List (icon) settings'
  type: mapping

field.value.list_icon:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Value'
